### ISSUE TITLE
Bower package naming.

### ISSUE THREAD

**Issue by aciid** [Luegg/angularjs-scroll-glue#12]
Hey I love your directive, just found it through google.

A couple of notes, your bower.json says package name is "angularjs-scroll-glue". 
And in the bower database it's "angularjs-scroll-glue-Luegg". 

For naming policys sake, could you rename into "angular-scroll-glue". 
Angularjs libraries tend to use "angular" prefix.

Also by changing the name you could reclaim your version as the REAL package, I see that a old fork has reclaimed your name. Which is just silly, as you keep your package up-to-date, wishbear aka prettynatty could remove his.

 
    ➜  chat git:(master) ✗ bower search scroll-glue
      Search results:

    angularjs-scroll-glue git://github.com/wishbear/angularjs-scroll-glue.git
    angularjs-scroll-glue-Luegg git://github.com/Luegg/angularjs-scroll-glue.git

Kind regards Aciid ~

**Comment by Luegg** [comment]
I've just renamed everything to angular-scroll-glue and re-registered the package under this name. Hope this helps and eventually we can get rid of the two old entries in the bower registry.

**Comment by williamboman** [comment]
It would probably be good to keep the old `angularjs-scroll-glue-Luegg` on bower for legacy reasons.

**Comment by tjsail33** [comment]
Seconded, just ran into build issues because angularjs-scroll-glue-Luegg wasnt available on bower anymore.
