### ISSUE TITLE
npm support please?

### ISSUE THREAD

**Issue by varmint09** [Luegg/angularjs-scroll-glue#24]
Hi,

Could you publish this as an npm package too please?

**Comment by Luegg** [comment]
@alejonext already did: https://www.npmjs.com/package/angularjs-scroll-glue

**Comment by varmint09** [comment]
Probably wise to update the documentation to mention that as an installation option?

Many thanks though, its a very useful plugin.

**Comment by alejonext** [comment]
Well.... @varmint09 is update!!

**Comment by Luegg** [comment]
I've also updated the readme

**Comment by alejonext** [comment]
But I can not update the NPM, because I will require a new version. Well, it will be for the next version
