### ISSUE TITLE
Is there a way to scroll to bottom after scrolling up manually

### ISSUE THREAD

**Issue by cmacdonnacha** [Luegg/angularjs-scroll-glue#30]
Scenario:

1.) Div is set to "scroll-glue"
2.) Add multiple items to list and stays scrolled to bottom
3.) Manually scroll up to top
4.) Add another item

After the item at step 4 is added should the div be scrolled back down to bottom?
Currently is stays at the top.

**Comment by germanger** [comment]
I'm actually getting the contrary behavior: after your (4), my scroll goes to the bottom.

But I'd love to see an option for specifying the desired behavior, because **I do want** the behavior you are getting.

**Comment by germanger** [comment]
Ah! found the solution by looking at the Plunker

This will always scroll to bottom (what you want)

        <div scroll-glue="true">...</div>

This will scroll to bottom if it is already at bottom but not if manually scrolled up (what I want)

        <div scroll-glue>...</div>

**Comment by cmacdonnacha** [comment]
Ok great. I'll give that a go.
