### ISSUE TITLE
NPM Parity

### ISSUE THREAD

**Issue by Smolations** [Luegg/angularjs-scroll-glue#40]
Currently, v2.0.6 is available via bower, but npm only has 2.0.4 as the most recent version. I noticed that the maintainer for the npm package is not you. Was it deliberate or did that guy just register his package before you could?

In any case, keeping both package manager versions of your module would be ideal. If there's any way you can make that happen, you would be my hero! :smile:

**Comment by Smolations** [comment]
Is this project still being maintained? Not sure if this comment was seen given the date of the original post.   =[

**Comment by oliversalzburg** [comment]
I just published v2.0.7 to npm. Please let us know if there are any issues :)

**Comment by Smolations** [comment]
Thank you!
