### ISSUE TITLE
Does not scroll to the bottom until scrollable dom is modified when scroll contrainer is hidden with ng-hide and then shown

### ISSUE THREAD

**Issue by Jonnx** [Luegg/angularjs-scroll-glue#41]
For some reason the scroll-glue plugin does not work when the scroll container is hidden at page load and the scrollable content is loaded in with an async request post page render.

let me know if you have any more questions / i can help in any way

**Comment by IgorFenixApps** [comment]
+1

**Comment by bbougot** [comment]
+1

**Comment by supersnager** [comment]
Jonnx: I'm not tested your issue, but you can try my today fix. I think it maybe can help:
https://github.com/supersnager/angularjs-scroll-glue

**Comment by rrejc** [comment]
I had similar problem, container was not scrolled to the bottom. @supersnager 's fix worked for me.

**Comment by chris-wood-dynmark** [comment]
+1 supersnager, thank you
