### ISSUE TITLE
How to do ES6 import?

### ISSUE THREAD

**Issue by cen1** [Luegg/angularjs-scroll-glue#47]
I am trying to import this module in the following way:
1. Added to package.json
2. In app.js I added `import luegg from 'angularjs-scroll-glue'`
3. And then

```
export let app = angular.module('mymodule', [
   ...some other modules...
    luegg.directives,
]);
```

But console throws: Error: [$injector:modulerr] Failed to instantiate module mymodule due to:
[$injector:modulerr] Failed to instantiate module undefined due to:
[ng:areq] Argument 'module' is not a function, got undefined

It seems that it actually wants to load it but fails. Am I doing something wrong and is there any way I can make this work?

**Comment by CovertIII** [comment]
You can put quotes around it

```
import luegg from 'angularjs-scroll-glue'
export let app = angular.module('mymodule', [
   ...some other modules...
    'luegg.directives',
]);
```
 or just use the variable with no dot
```
import luegg from 'angularjs-scroll-glue'
export let app = angular.module('mymodule', [
   ...some other modules...
    luegg,
]);
```

**Comment by oliversalzburg** [comment]
@CovertIII Thanks
