### ISSUE TITLE
Maintaining this module

### ISSUE THREAD

**Issue by oliversalzburg** [Luegg/angularjs-scroll-glue#48]
I would be interested in taking over maintenance of this module. Please get in touch with me if you're interested.

**Comment by Luegg** [comment]
Hi Oliver

I would really appreciate if someone would take this over. Can you just fork the repo or do you need access to this repo in order to maintain the bower and npm packages?

**Comment by oliversalzburg** [comment]
@Luegg Preferably, you would set me as a collaborator of this repo at https://github.com/Luegg/angularjs-scroll-glue/settings/collaboration

The bower package points to this repo here on GitHub, so any new tags that would be pushed here, would work automatically.

I don't know which npm package is the correct one for this repo, as both [angularjs-scroll-glue](https://www.npmjs.com/package/angularjs-scroll-glue) and [ng-scroll-glue](https://www.npmjs.com/package/ng-scroll-glue) seem to be maintained by other people.

In case angularjs-scroll-glue belongs to you, `npm owner add oliversalzburg angularjs-scroll-glue` should work.

**Comment by Luegg** [comment]
Welcome on board :-)

Unfortunately, I'm not the owner of angularjs-scroll-glue, but I guess it's the one published with this repo.

**Comment by oliversalzburg** [comment]
I'll contact the owner of angularjs-scroll-glue and ask them for write access, if that fails, I would publish under a new name.

I'll try to look into open issues and PRs ASAP.

Cheers :)

**Comment by Luegg** [comment]
Awesome :-)

I’m sure people will be glad to see some progress here. For my part, I
started this project to experiment with some Angular features and never
used it in a real project. Thus, the incentive to work on it was not that
great.

2016-06-03 14:32 GMT+02:00 Oliver Salzburg <notifications@github.com>:

**Comment by oliversalzburg** [comment]
We've been using it in production for quite some time and have big interest in keeping it running :)

**Comment by oliversalzburg** [comment]
Would you mind sending me an email to my public address on my profile, so that I have your address?

I just wanted to throw a couple of questions your way. I'd also be fine with communicating through GitHub issues if you don't want to give out your email :)
